// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import EmergencyController from "./emergency_controller"
application.register("emergency", EmergencyController)

import FilterClinicController from "./filter_clinic_controller"
application.register("filter-clinic", FilterClinicController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
